### ISSUE TITLE
Error while typing a search keyword

### ISSUE THREAD

**Issue by yhagio** [RGRjs/rgrjs.com#1]
At line 15 in `/js/components/Main.js`

``` js
search = (e) => {
  let query = e.target.value; // this is always 'null'
  this.props.relay.setVariables({ query });
};
```

I get the error message in browser console:

```
Uncaught TypeError: Cannot read property 'value' of null
```

and the search function does not work.
It seems `debounce()` from lodash causes error but not sure why.

**Comment by pmould** [comment]
I have the same problem as @yhagio . I am using lodash 3.6.0;
The search is working without lodash but when i set debounce on this.search() I get the following error:

```
Uncaught TypeError: Cannot read property 'value' of null
Main._this.search @ Main.js:16
complete @ index.js:7697
delayed @ index.js:7707
```

**Comment by samerbuna** [comment]
React has special performance behaviour when it comes to browser events. Using the target asynchronously should be avoided.

Here's a better way to doing the debouncing for this case:

https://github.com/RGRjs/rgrjs.com/commit/d2898b5c1877aa91dbbb0340d6937e13e0b7612d
