### ISSUE TITLE
Optimistic Updates not working

### ISSUE THREAD

**Issue by pmould** [RGRjs/rgrjs.com#2]
Optimistic Update for a resource is not working when you create a resource. 
When you add a resource the following warning appears: 

```
Warning: writeRelayUpdatePayload(): Expected response payload to include the newly created edge 
`linkEdge` and its `node` field. Did you forget to update the `RANGE_ADD` mutation config?
```

The optimistic updates work when your remove the custom param `query: $query` from the GraphQL query parameters for the Link Mutation.

Basically the implementation of the search query breaks the code for the optimistic updates for resources

**Comment by guzart** [comment]
This is a known bug:

https://github.com/facebook/relay/issues/477

The work around is to use 'REQUIRED_CHILDREN' config.

```
{
  type: 'REQUIRED_CHILDREN',
  children: [
    Relay.QL`
      fragment on CreateLinkPayload {
        linkEdge {
          cursor,
        }
      }
    `
  ]
}
```

**Comment by samerbuna** [comment]
Hopefully, https://github.com/facebook/relay/issues/538 will solve this problem:
