### ISSUE TITLE
I get this all the time if i run the commands you specified. I don't know whether it is babel issue or not

### ISSUE THREAD

**Issue by tspanindra** [RGRjs/rgrjs.com#3]
ERROR in ./js/app.js
Module build failed: ReferenceError: Unknown plugin "./babelRelayPlugin" specified in "base" at 0,

**Comment by mainsy** [comment]
I get this error also. As I was following along doing the pluralsight course I couldn't get past this issue. It would work if I declared it as '../babelRelayPlugin' the first time, but anytime Relay.QL is used it would try to execute the plugin relative to the directory it was called from. So the 2nd time it was no longer an accurate location for the plugin.

I downloaded this repo as a zip and ran npm install and webpack -wd and it won't build the bundle.

**Comment by shashwattt-Pretlist** [comment]
Had the same issue, got fixed with -- "plugins: ['./babelRelayPlugin'].map(require.resolve)" in webpack.config.js

**Comment by maksugr** [comment]
Also it could be fixed if you'll have something like that in your webpack.config.js

```
module.exports= {
    entry: './js/app.js',
    output: {
        path: __dirname + '/public',
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    presets: ['react', 'es2015', 'stage-0'],
                    plugins: [__dirname+ '/babelRelayPlugin']
                }
            }
        ]
    }
};
```

I'm talking about line `plugins: [__dirname+ '/babelRelayPlugin']`.

**Comment by karuppiah7890** [comment]
Thanks a lot @maksugr ! 

@samerbuna Please merge this important PR !!!!!!

**Comment by samerbuna** [comment]
Fixed. Thanks for pointing that out.
